<?php

declare(strict_types=1);

namespace Trilobit\Shop\Presentation\Admin;

/**
 * Makes the list of products for Trilobit\Shop\Presentation\Admin\ProductPresenter.
 *
 * Generated by the container (see ShopExtension), so that the presenter is
 * handed the one thing it draws rather than the services the list is made of.
 */
interface ProductListingFactory
{
    public function create(): ProductListing;
}
