<?php

declare(strict_types=1);

namespace Trilobit\Tests\Integration\Console;

use Doctrine\ORM\EntityManagerInterface;
use Nette\DI\Container;
use Nette\Security\Authenticator;
use Nette\Security\User as SignedIn;
use PHPUnit\Framework\Attributes\CoversNothing;
use PHPUnit\Framework\TestCase;
use Symfony\Component\Console\Application;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Tester\CommandTester;
use Trilobit\Core\Bootstrap;
use Trilobit\Core\Console\AccountCommand;
use Trilobit\Core\Domain\Tenancy\Membership;
use Trilobit\Core\Domain\Tenancy\Tenant;
use Trilobit\Core\Domain\User\Role;
use Trilobit\Core\Domain\User\User;
use Trilobit\Core\Security\Accounts;
use Trilobit\Core\Security\Identity;
use Trilobit\Core\Security\Landlords;
use Trilobit\Core\Security\Permissions;
use Trilobit\Core\Security\PermissionStructure;
use Trilobit\Core\Security\Privilege;
use Trilobit\Core\Security\Resource;
use Trilobit\Tests\Boot;
use Trilobit\Tests\Database;
use Trilobit\Tests\Migrations;
use Trilobit\Tests\Tenants;

/**
 * `bin/trilobit app:account`, which is how a fresh installation gets somebody
 * who can sign in - and how it says which of the two kinds of administrator it
 * means.
 *
 * The two are different scopes rather than different levels. Without --tenant
 * the account administers the installation: no business, no role, no
 * membership. With --tenant it administers the one business answering at that
 * host, which means the account, the role, and the membership joining them -
 * the only place a right is ever written down. With --also-installation beside
 * --tenant it is both, and without that switch it is never both. An earlier
 * build made neither of those and left the first account of a fresh
 * installation able to sign in and do nothing, which is the finding this
 * asserts is gone.
 *
 * The password is generated by the command and printed once. It is never an
 * argument, because an argument is visible in the process list of the machine
 * it is typed on, and it is never stored anywhere but as a hash.
 *
 * The shape of that one line is asserted here on purpose. tests/e2e reads the
 * password back out of this output in order to sign in with a real browser, so
 * the format is a contract between the command and that suite; without a test
 * on it, changing the wording would break the browser suite for a reason
 * nobody would look for in this file.
 */
#[CoversNothing]
final class AccountCommandTest extends TestCase
{
    /** The host the business in this fixture answers at, and therefore what --tenant is given. */
    private const string HOST = 'bikes.example.com';

    private string $schema = '';

    private ?Container $container = null;

    protected function tearDown(): void
    {
        $this->container?->getByType(SignedIn::class)->logout(true);
        $this->container = null;

        if ($this->schema !== '') {
            Database::drop($this->schema);
            $this->schema = '';
        }
    }

    /**
     * Named without a business, the account is the one above them all: it holds
     * no role anywhere, because a role is held in a business and this one is in
     * none.
     */
    public function testWithoutABusinessItMakesTheAdministratorOfTheInstallation(): void
    {
        $container = $this->emptyInstallation();

        $output = $this->execute($container, 'alice@example.com');
        $password = $this->passwordIn($output);

        $identity = $container->getByType(Authenticator::class)->authenticate('alice@example.com', $password);

        self::assertInstanceOf(Identity::class, $identity);
        self::assertSame([], $identity->getRoles());
        self::assertSame([], $identity->permissions());

        $account = $container->getByType(Accounts::class)->withEmail('alice@example.com');
        self::assertInstanceOf(User::class, $account);
        self::assertTrue($account->isLandlord());

        $entityManager = $container->getByType(EntityManagerInterface::class);
        self::assertCount(0, $entityManager->getRepository(Role::class)->findAll());

        Tenants::switchTo($container, $this->business($container));
        self::assertCount(0, $entityManager->getRepository(Membership::class)->findAll());
    }

    /**
     * Named with a business, all three rows appear - the account, the role and
     * the membership joining them in that business. The membership is the one
     * that matters: it is the only place a right is written down, and an
     * earlier build wrote none of them.
     */
    public function testWithABusinessItMakesAnAdministratorInsideIt(): void
    {
        $container = $this->emptyInstallation();

        $this->execute($container, 'alice@example.com', tenant: self::HOST);

        $account = $container->getByType(Accounts::class)->withEmail('alice@example.com');
        self::assertInstanceOf(User::class, $account);
        self::assertFalse($account->isLandlord());
        self::assertSame([], $account->roleCodes(), 'nothing is granted globally; a right is held in a business');

        $memberships = $container->getByType(EntityManagerInterface::class)
            ->getRepository(Membership::class)
            ->findAll();

        self::assertCount(1, $memberships);
        self::assertSame('alice@example.com', $memberships[0]->user()->email());
        self::assertSame('owner', $memberships[0]->role()->code());
        self::assertSame('Ammonite Bikes', $memberships[0]->tenant()->name());
    }

    /**
     * The claim the three rows are there for, asked the way the application
     * asks it, and asked of every pair this build offers. Counting rows would
     * pass just as well for a role assembled out of pieces nothing offers,
     * which is exactly what an earlier build wrote; naming a few pairs would
     * pass for a role that had merely fallen behind.
     */
    public function testTheOwnerOfABusinessMayDoEverythingInIt(): void
    {
        $container = $this->emptyInstallation();

        $password = $this->passwordIn($this->execute($container, 'alice@example.com', tenant: self::HOST));
        $container->getByType(SignedIn::class)->login('alice@example.com', $password);

        $permissions = $container->getByType(Permissions::class);

        $pairs = PermissionStructure::of(Bootstrap::rootDirectory())->everyPair();
        self::assertNotSame([], $pairs);

        foreach ($pairs as $pair) {
            $privilege = $pair->privilege;
            self::assertInstanceOf(Privilege::class, $privilege);
            self::assertTrue(
                $permissions->isAllowed($pair->resource, $privilege),
                'the owner was refused ' . $pair->code(),
            );
        }
    }

    /**
     * The role is the owner's, and it is the whole of the application rather
     * than a list of what this build offers: a list goes on saying what the
     * application used to offer, and the whole of it takes in every section
     * added afterwards without anybody coming back to the role.
     */
    public function testTheRoleIsTheOwnersAndHoldsTheWholeApplication(): void
    {
        $container = $this->emptyInstallation();

        $this->execute($container, 'alice@example.com', tenant: self::HOST);

        $role = $container->getByType(Accounts::class)->roleWithCode('owner');
        self::assertInstanceOf(Role::class, $role);
        self::assertSame('Owner', $role->name());
        self::assertSame(['app:*'], $role->permissions());
    }

    /**
     * A row under the owner's code that says anything else is brought back to
     * the whole of the application on every run - here a single pair, the
     * shape a hand-edited row or an earlier build could leave behind. Leaving
     * it alone would hand the account a role that reaches less than owning a
     * business means, which looks like a permission problem rather than like
     * an old row.
     */
    public function testItBringsTheOwnersRoleBackToTheWholeApplication(): void
    {
        $container = $this->emptyInstallation();

        $entityManager = $container->getByType(EntityManagerInterface::class);
        $entityManager->persist(new Role('owner', 'Owner', ['app.administration:view']));
        $entityManager->flush();

        $this->execute($container, 'alice@example.com', tenant: self::HOST);

        $role = $container->getByType(Accounts::class)->roleWithCode('owner');
        self::assertInstanceOf(Role::class, $role);
        self::assertSame(['app:*'], $role->permissions());
        self::assertCount(1, $entityManager->getRepository(Role::class)->findAll(), 'the row was reused, not doubled');
    }

    /**
     * A host nobody has claimed is refused rather than quietly given a business
     * of its own. Two ways to create one is one too many, and the one that
     * happens by accident is the wrong one.
     */
    public function testAHostNoBusinessAnswersAtIsRefused(): void
    {
        $container = $this->emptyInstallation();

        [$status, $output] = $this->outcomeOf($container, 'alice@example.com', tenant: 'nobody.example.org');

        self::assertSame(Command::FAILURE, $status, $output);
        self::assertStringContainsString('nobody.example.org', $output);
        self::assertNull($container->getByType(Accounts::class)->withEmail('alice@example.com'));
    }

    /**
     * The two scopes must not meet by accident, and this is the half a
     * command can refuse: an account that administers the installation is not
     * given a role in a business because a business was named. The other half
     * - a member of a business becoming the installation's administrator - is
     * below, and the deeper refusal is in the constructor of
     * Trilobit\Core\Domain\Tenancy\Membership, where no caller can go round it
     * without naming the way that says so.
     */
    public function testTheAdministratorOfTheInstallationIsNotAlsoGivenABusiness(): void
    {
        $container = $this->emptyInstallation();
        $this->execute($container, 'alice@example.com');

        [$status, $output] = $this->outcomeOf($container, 'alice@example.com', tenant: self::HOST);

        self::assertSame(Command::FAILURE, $status, $output);
        self::assertStringContainsString('administers the installation', $output);

        Tenants::switchTo($container, $this->business($container));
        self::assertCount(
            0,
            $container->getByType(EntityManagerInterface::class)->getRepository(Membership::class)->findAll(),
        );
    }

    /** And the other way round: somebody administering a business is not made the installation's administrator. */
    public function testAnAdministratorOfABusinessIsNotAlsoMadeTheInstallations(): void
    {
        $container = $this->emptyInstallation();
        $this->execute($container, 'alice@example.com', tenant: self::HOST);

        [$status, $output] = $this->outcomeOf($container, 'alice@example.com');

        self::assertSame(Command::FAILURE, $status, $output);
        self::assertStringContainsString('administers a business', $output);

        $account = $container->getByType(Accounts::class)->withEmail('alice@example.com');
        self::assertInstanceOf(User::class, $account);
        self::assertFalse($account->isLandlord());
    }

    /**
     * The refusal above names the way to say it. Being both is allowed now,
     * but only as something somebody decided, so the command that is not told
     * says which switch would have told it rather than doing it anyway.
     */
    public function testTheRefusalNamesTheSwitchThatSaysItOutright(): void
    {
        $container = $this->emptyInstallation();
        $this->execute($container, 'alice@example.com');

        [$status, $output] = $this->outcomeOf($container, 'alice@example.com', tenant: self::HOST);

        self::assertSame(Command::FAILURE, $status, $output);
        self::assertStringContainsString('--also-installation', $output);
    }

    /**
     * Said outright, the administrator of the installation is made the owner
     * of a business as well, and is then both: answered yes about the
     * installation, and asked about in the business as the member it now is.
     */
    public function testSaidOutrightTheInstallationsAdministratorOwnsABusinessAsWell(): void
    {
        $container = $this->emptyInstallation();
        $this->execute($container, 'alice@example.com');

        $output = $this->execute($container, 'alice@example.com', tenant: self::HOST, alsoInstallation: true);

        $account = $container->getByType(Accounts::class)->withEmail('alice@example.com');
        self::assertInstanceOf(User::class, $account);
        self::assertTrue($account->isLandlord(), 'being given a business took the installation away');

        $memberships = $container->getByType(EntityManagerInterface::class)
            ->getRepository(Membership::class)
            ->findAll();
        self::assertCount(1, $memberships);
        self::assertSame('owner', $memberships[0]->role()->code());
        self::assertSame('Ammonite Bikes', $memberships[0]->tenant()->name());

        $container->getByType(SignedIn::class)->login('alice@example.com', $this->passwordIn($output));
        self::assertTrue($container->getByType(Landlords::class)->isLandlord());
        self::assertTrue($container->getByType(Permissions::class)->isAllowed(Resource::Administration, Privilege::View));
    }

    /**
     * A new account can be made both at once - the first account of a simple
     * installation, where one person runs the one shop - and running it again
     * leaves one account and one membership, as the other shapes do.
     */
    public function testANewAccountIsMadeBothWhenThatIsSaid(): void
    {
        $container = $this->emptyInstallation();

        $output = $this->execute($container, 'alice@example.com', tenant: self::HOST, alsoInstallation: true);
        $this->execute($container, 'alice@example.com', tenant: self::HOST, alsoInstallation: true);

        self::assertStringContainsString('administers the installation', $output);
        self::assertStringContainsString('Ammonite Bikes', $output);

        $account = $container->getByType(Accounts::class)->withEmail('alice@example.com');
        self::assertInstanceOf(User::class, $account);
        self::assertTrue($account->isLandlord());

        $entityManager = $container->getByType(EntityManagerInterface::class);
        self::assertCount(1, $entityManager->getRepository(User::class)->findAll());
        self::assertCount(1, $entityManager->getRepository(Membership::class)->findAll());
    }

    /**
     * The switch says "a business as well", so without a business it says
     * nothing and is refused rather than quietly meaning the installation
     * alone - which is what leaving --tenant out already means.
     */
    public function testTheSwitchWithoutABusinessIsRefused(): void
    {
        $container = $this->emptyInstallation();

        [$status, $output] = $this->outcomeOf($container, 'alice@example.com', alsoInstallation: true);

        self::assertSame(Command::FAILURE, $status, $output);
        self::assertStringContainsString('--tenant', $output);
        self::assertNull($container->getByType(Accounts::class)->withEmail('alice@example.com'));
    }

    /**
     * What the switch does not do is make an existing member of a business the
     * installation's administrator. Whether an account administers the
     * installation is said when it is made - see
     * Trilobit\Core\Domain\User\User - and the switch is not a way to say it
     * afterwards.
     */
    public function testAnAdministratorOfABusinessIsNotMadeBothAfterwards(): void
    {
        $container = $this->emptyInstallation();
        $this->execute($container, 'alice@example.com', tenant: self::HOST);

        [$status, $output] = $this->outcomeOf($container, 'alice@example.com', tenant: self::HOST, alsoInstallation: true);

        self::assertSame(Command::FAILURE, $status, $output);
        self::assertStringContainsString('administers a business', $output);

        $account = $container->getByType(Accounts::class)->withEmail('alice@example.com');
        self::assertInstanceOf(User::class, $account);
        self::assertFalse($account->isLandlord());
    }

    /** The password is shown once and nowhere else; the rest of the output is prose. */
    public function testThePasswordIsShownExactlyOnce(): void
    {
        $container = $this->emptyInstallation();

        $output = $this->execute($container, 'alice@example.com');

        self::assertSame(1, preg_match_all(AccountCommand::PASSWORD_LINE, $output));
    }

    /** And the same holds for the other shape, which prints one line more. */
    public function testThePasswordIsShownExactlyOnceForAnAdministratorOfABusinessToo(): void
    {
        $container = $this->emptyInstallation();

        $output = $this->execute($container, 'alice@example.com', tenant: self::HOST);

        self::assertSame(1, preg_match_all(AccountCommand::PASSWORD_LINE, $output));
    }

    public function testItNamesTheAccountWhenAskedTo(): void
    {
        $container = $this->emptyInstallation();

        $this->execute($container, 'alice@example.com', name: 'Alice Ammonite');

        $account = $container->getByType(Accounts::class)->withEmail('alice@example.com');

        self::assertInstanceOf(User::class, $account);
        self::assertSame('Alice Ammonite', $account->name());
    }

    /**
     * Run twice, it replaces the password of the account that is there rather
     * than refusing or making a second one - which is what a deployment script
     * calling it on every deploy needs, and what somebody who has forgotten
     * their password needs too.
     */
    public function testRunningItAgainReplacesThePasswordAndLeavesOneAccount(): void
    {
        $container = $this->emptyInstallation();

        $first = $this->passwordIn($this->execute($container, 'alice@example.com'));
        $second = $this->passwordIn($this->execute($container, 'alice@example.com'));

        self::assertNotSame($first, $second);

        $authenticator = $container->getByType(Authenticator::class);
        $identity = $authenticator->authenticate('alice@example.com', $second);
        self::assertInstanceOf(Identity::class, $identity);

        $entityManager = $container->getByType(EntityManagerInterface::class);
        self::assertCount(1, $entityManager->getRepository(User::class)->findAll());
        self::assertCount(0, $entityManager->getRepository(Role::class)->findAll());
    }

    /**
     * The same for the other shape, where running twice could also leave a
     * second role or a second membership - the second of which the database
     * would refuse, loudly, in the middle of a deployment.
     */
    public function testRunningItAgainForABusinessLeavesOneRoleAndOneMembership(): void
    {
        $container = $this->emptyInstallation();

        $this->execute($container, 'alice@example.com', tenant: self::HOST);
        $this->execute($container, 'alice@example.com', tenant: self::HOST);

        $entityManager = $container->getByType(EntityManagerInterface::class);

        self::assertCount(1, $entityManager->getRepository(User::class)->findAll());
        self::assertCount(1, $entityManager->getRepository(Role::class)->findAll());
        self::assertCount(1, $entityManager->getRepository(Membership::class)->findAll());
    }

    /**
     * A fresh installation with one business in it, and nothing entered yet:
     * the command is what says which business it means, from the host it is
     * given.
     */
    private function emptyInstallation(): Container
    {
        $this->schema = Database::schemaFor(self::class);
        $container = Boot::coreAlone();
        Migrations::run($container);
        Tenants::create($container, 'Ammonite Bikes', self::HOST);

        // The signed-in user is asked for so that the container builds the
        // security services the same way a request would; the command itself
        // does not use it.
        self::assertInstanceOf(SignedIn::class, $container->getByType(SignedIn::class));

        return $this->container = $container;
    }

    private function business(Container $container): Tenant
    {
        $tenant = $container->getByType(EntityManagerInterface::class)
            ->getRepository(Tenant::class)
            ->findOneBy(['name' => 'Ammonite Bikes']);

        self::assertInstanceOf(Tenant::class, $tenant);

        return $tenant;
    }

    private function execute(
        Container $container,
        string $email,
        string $name = '',
        string $tenant = '',
        bool $alsoInstallation = false,
    ): string {
        [$status, $output] = $this->outcomeOf($container, $email, $name, $tenant, $alsoInstallation);

        self::assertSame(Command::SUCCESS, $status, $output);

        return $output;
    }

    /** @return array{int, string} */
    private function outcomeOf(
        Container $container,
        string $email,
        string $name = '',
        string $tenant = '',
        bool $alsoInstallation = false,
    ): array {
        $command = $container->getService('core.accountCommand');
        self::assertInstanceOf(Command::class, $command);
        new Application()->addCommand($command);

        $tester = new CommandTester($command);
        $arguments = ['email' => $email];
        if ($name !== '') {
            $arguments['--name'] = $name;
        }

        if ($tenant !== '') {
            $arguments['--tenant'] = $tenant;
        }

        if ($alsoInstallation) {
            $arguments['--also-installation'] = true;
        }

        $status = $tester->execute($arguments, ['capture_stderr_separately' => true]);

        return [$status, $tester->getDisplay() . $tester->getErrorOutput()];
    }

    private function passwordIn(string $output): string
    {
        preg_match(AccountCommand::PASSWORD_LINE, $output, $match);
        $password = $match[1] ?? '';

        self::assertNotSame('', $password, 'the command printed nothing to sign in with: ' . $output);

        return $password;
    }
}
