<?php

declare(strict_types=1);

namespace Trilobit\Tests\Integration\Console;

use Doctrine\DBAL\Connection;
use Doctrine\ORM\EntityManagerInterface;
use Nette\DI\Container;
use Nette\Security\Authenticator;
use Nette\Security\User as SignedIn;
use PHPUnit\Framework\Attributes\CoversNothing;
use PHPUnit\Framework\TestCase;
use Symfony\Component\Console\Application;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Tester\CommandTester;
use Trilobit\Core\Bootstrap;
use Trilobit\Core\Console\AccountCommand;
use Trilobit\Core\Domain\Tenancy\Membership;
use Trilobit\Core\Domain\Tenancy\Tenant;
use Trilobit\Core\Domain\User\Role;
use Trilobit\Core\Domain\User\User;
use Trilobit\Core\Security\Accounts;
use Trilobit\Core\Security\Identity;
use Trilobit\Core\Security\Landlords;
use Trilobit\Core\Security\Permissions;
use Trilobit\Core\Security\PermissionStructure;
use Trilobit\Core\Security\Privilege;
use Trilobit\Core\Security\Resource;
use Trilobit\Tests\Boot;
use Trilobit\Tests\Database;
use Trilobit\Tests\Migrations;
use Trilobit\Tests\Tenants;

/**
 * `bin/trilobit app:account`, which is how a fresh installation gets somebody
 * who can sign in - and how it says which of the two kinds of administrator it
 * means.
 *
 * The two are different scopes rather than different levels. Without --tenant
 * the account administers the installation: no business, no role, no
 * membership. With --tenant it administers the one business answering at that
 * host, which means the account, the role, and the membership joining them -
 * the only place a right is ever written down. With --also-installation beside
 * --tenant it is both, and without that switch it is never both. An earlier
 * build made neither of those and left the first account of a fresh
 * installation able to sign in and do nothing, which is the finding this
 * asserts is gone.
 *
 * The password is generated by the command and printed once. It is never an
 * argument, because an argument is visible in the process list of the machine
 * it is typed on, and it is never stored anywhere but as a hash.
 *
 * The shape of that one line is asserted here on purpose. tests/e2e reads the
 * password back out of this output in order to sign in with a real browser, so
 * the format is a contract between the command and that suite; without a test
 * on it, changing the wording would break the browser suite for a reason
 * nobody would look for in this file.
 */
#[CoversNothing]
final class AccountCommandTest extends TestCase
{
    /** The host the business in this fixture answers at, and therefore what --tenant is given. */
    private const string HOST = 'bikes.example.com';

    /**
     * How long a command in a process of its own gets to reach the insert of
     * the owner's role. It boots the application first, which is seconds and
     * not minutes, and the lock it then waits on gives up by itself after
     * innodb_lock_wait_timeout - fifty seconds unless the server says less.
     */
    private const int SECONDS_TO_REACH_THE_INSERT = 30;

    private string $schema = '';

    private ?Container $container = null;

    protected function tearDown(): void
    {
        $this->container?->getByType(SignedIn::class)->logout(true);
        $this->container = null;

        if ($this->schema !== '') {
            Database::drop($this->schema);
            $this->schema = '';
        }
    }

    /**
     * Named without a business, the account is the one above them all: it holds
     * no role anywhere, because a role is held in a business and this one is in
     * none.
     */
    public function testWithoutABusinessItMakesTheAdministratorOfTheInstallation(): void
    {
        $container = $this->emptyInstallation();

        $output = $this->execute($container, 'alice@example.com');
        $password = $this->passwordIn($output);

        $identity = $container->getByType(Authenticator::class)->authenticate('alice@example.com', $password);

        self::assertInstanceOf(Identity::class, $identity);
        self::assertSame([], $identity->getRoles());
        self::assertSame([], $identity->permissions());

        $account = $container->getByType(Accounts::class)->withEmail('alice@example.com');
        self::assertInstanceOf(User::class, $account);
        self::assertTrue($account->isLandlord());

        $entityManager = $container->getByType(EntityManagerInterface::class);
        self::assertCount(0, $entityManager->getRepository(Role::class)->findAll());

        Tenants::switchTo($container, $this->business($container));
        self::assertCount(0, $entityManager->getRepository(Membership::class)->findAll());
    }

    /**
     * Named with a business, all three rows appear - the account, the role and
     * the membership joining them in that business. The membership is the one
     * that matters: it is the only place a right is written down, and an
     * earlier build wrote none of them.
     */
    public function testWithABusinessItMakesAnAdministratorInsideIt(): void
    {
        $container = $this->emptyInstallation();

        $this->execute($container, 'alice@example.com', tenant: self::HOST);

        $account = $container->getByType(Accounts::class)->withEmail('alice@example.com');
        self::assertInstanceOf(User::class, $account);
        self::assertFalse($account->isLandlord());
        self::assertSame([], $account->roleCodes(), 'nothing is granted globally; a right is held in a business');

        $memberships = $container->getByType(EntityManagerInterface::class)
            ->getRepository(Membership::class)
            ->findAll();

        self::assertCount(1, $memberships);
        self::assertSame('alice@example.com', $memberships[0]->user()->email());
        self::assertSame('owner', $memberships[0]->role()->code());
        self::assertSame('Ammonite Bikes', $memberships[0]->tenant()->name());
    }

    /**
     * The claim the three rows are there for, asked the way the application
     * asks it, and asked of every pair this build offers. Counting rows would
     * pass just as well for a role assembled out of pieces nothing offers,
     * which is exactly what an earlier build wrote; naming a few pairs would
     * pass for a role that had merely fallen behind.
     */
    public function testTheOwnerOfABusinessMayDoEverythingInIt(): void
    {
        $container = $this->emptyInstallation();

        $password = $this->passwordIn($this->execute($container, 'alice@example.com', tenant: self::HOST));
        $container->getByType(SignedIn::class)->login('alice@example.com', $password);

        $permissions = $container->getByType(Permissions::class);

        $pairs = PermissionStructure::of(Bootstrap::rootDirectory())->everyPair();
        self::assertNotSame([], $pairs);

        foreach ($pairs as $pair) {
            $privilege = $pair->privilege;
            self::assertInstanceOf(Privilege::class, $privilege);
            self::assertTrue(
                $permissions->isAllowed($pair->resource, $privilege),
                'the owner was refused ' . $pair->code(),
            );
        }
    }

    /**
     * The role is the owner's, and it is the whole of the application rather
     * than a list of what this build offers: a list goes on saying what the
     * application used to offer, and the whole of it takes in every section
     * added afterwards without anybody coming back to the role.
     */
    public function testTheRoleIsTheOwnersAndHoldsTheWholeApplication(): void
    {
        $container = $this->emptyInstallation();

        $this->execute($container, 'alice@example.com', tenant: self::HOST);

        $role = $container->getByType(Accounts::class)->roleWithCode('owner');
        self::assertInstanceOf(Role::class, $role);
        self::assertSame('Owner', $role->name());
        self::assertSame(['app:*'], $role->permissions());
    }

    /**
     * A row under the owner's code that says anything else is brought back to
     * the whole of the application on every run - here a single pair, the
     * shape a hand-edited row or an earlier build could leave behind. Leaving
     * it alone would hand the account a role that reaches less than owning a
     * business means, which looks like a permission problem rather than like
     * an old row.
     */
    public function testItBringsTheOwnersRoleBackToTheWholeApplication(): void
    {
        $container = $this->emptyInstallation();

        $entityManager = $container->getByType(EntityManagerInterface::class);
        $entityManager->persist(new Role('owner', 'Owner', ['app.administration:view']));
        $entityManager->flush();

        $this->execute($container, 'alice@example.com', tenant: self::HOST);

        $role = $container->getByType(Accounts::class)->roleWithCode('owner');
        self::assertInstanceOf(Role::class, $role);
        self::assertSame(['app:*'], $role->permissions());
        self::assertCount(1, $entityManager->getRepository(Role::class)->findAll(), 'the row was reused, not doubled');
    }

    /**
     * A host nobody has claimed is refused rather than quietly given a business
     * of its own. Two ways to create one is one too many, and the one that
     * happens by accident is the wrong one.
     */
    public function testAHostNoBusinessAnswersAtIsRefused(): void
    {
        $container = $this->emptyInstallation();

        [$status, $output] = $this->outcomeOf($container, 'alice@example.com', tenant: 'nobody.example.org');

        self::assertSame(Command::FAILURE, $status, $output);
        self::assertStringContainsString('nobody.example.org', $output);
        self::assertNull($container->getByType(Accounts::class)->withEmail('alice@example.com'));
    }

    /**
     * The two scopes must not meet by accident, and this is the half a
     * command can refuse: an account that administers the installation is not
     * given a role in a business because a business was named. The other half
     * - a member of a business becoming the installation's administrator - is
     * below, and the deeper refusal is in the constructor of
     * Trilobit\Core\Domain\Tenancy\Membership, where no caller can go round it
     * without naming the way that says so.
     */
    public function testTheAdministratorOfTheInstallationIsNotAlsoGivenABusiness(): void
    {
        $container = $this->emptyInstallation();
        $this->execute($container, 'alice@example.com');

        [$status, $output] = $this->outcomeOf($container, 'alice@example.com', tenant: self::HOST);

        self::assertSame(Command::FAILURE, $status, $output);
        self::assertStringContainsString('administers the installation', $output);

        Tenants::switchTo($container, $this->business($container));
        self::assertCount(
            0,
            $container->getByType(EntityManagerInterface::class)->getRepository(Membership::class)->findAll(),
        );
    }

    /** And the other way round: somebody administering a business is not made the installation's administrator. */
    public function testAnAdministratorOfABusinessIsNotAlsoMadeTheInstallations(): void
    {
        $container = $this->emptyInstallation();
        $this->execute($container, 'alice@example.com', tenant: self::HOST);

        [$status, $output] = $this->outcomeOf($container, 'alice@example.com');

        self::assertSame(Command::FAILURE, $status, $output);
        self::assertStringContainsString('administers a business', $output);

        $account = $container->getByType(Accounts::class)->withEmail('alice@example.com');
        self::assertInstanceOf(User::class, $account);
        self::assertFalse($account->isLandlord());
    }

    /**
     * The refusal above names the way to say it. Being both is allowed now,
     * but only as something somebody decided, so the command that is not told
     * says which switch would have told it rather than doing it anyway.
     */
    public function testTheRefusalNamesTheSwitchThatSaysItOutright(): void
    {
        $container = $this->emptyInstallation();
        $this->execute($container, 'alice@example.com');

        [$status, $output] = $this->outcomeOf($container, 'alice@example.com', tenant: self::HOST);

        self::assertSame(Command::FAILURE, $status, $output);
        self::assertStringContainsString('--also-installation', $output);
    }

    /**
     * Said outright, the administrator of the installation is made the owner
     * of a business as well, and is then both: answered yes about the
     * installation, and asked about in the business as the member it now is.
     */
    public function testSaidOutrightTheInstallationsAdministratorOwnsABusinessAsWell(): void
    {
        $container = $this->emptyInstallation();
        $this->execute($container, 'alice@example.com');

        $output = $this->execute($container, 'alice@example.com', tenant: self::HOST, alsoInstallation: true);

        $account = $container->getByType(Accounts::class)->withEmail('alice@example.com');
        self::assertInstanceOf(User::class, $account);
        self::assertTrue($account->isLandlord(), 'being given a business took the installation away');

        $memberships = $container->getByType(EntityManagerInterface::class)
            ->getRepository(Membership::class)
            ->findAll();
        self::assertCount(1, $memberships);
        self::assertSame('owner', $memberships[0]->role()->code());
        self::assertSame('Ammonite Bikes', $memberships[0]->tenant()->name());

        $container->getByType(SignedIn::class)->login('alice@example.com', $this->passwordIn($output));
        self::assertTrue($container->getByType(Landlords::class)->isLandlord());
        self::assertTrue($container->getByType(Permissions::class)->isAllowed(Resource::Administration, Privilege::View));
    }

    /**
     * A new account can be made both at once - the first account of a simple
     * installation, where one person runs the one shop - and running it again
     * leaves one account and one membership, as the other shapes do.
     */
    public function testANewAccountIsMadeBothWhenThatIsSaid(): void
    {
        $container = $this->emptyInstallation();

        $output = $this->execute($container, 'alice@example.com', tenant: self::HOST, alsoInstallation: true);
        $this->execute($container, 'alice@example.com', tenant: self::HOST, alsoInstallation: true);

        self::assertStringContainsString('administers the installation', $output);
        self::assertStringContainsString('Ammonite Bikes', $output);

        $account = $container->getByType(Accounts::class)->withEmail('alice@example.com');
        self::assertInstanceOf(User::class, $account);
        self::assertTrue($account->isLandlord());

        $entityManager = $container->getByType(EntityManagerInterface::class);
        self::assertCount(1, $entityManager->getRepository(User::class)->findAll());
        self::assertCount(1, $entityManager->getRepository(Membership::class)->findAll());
    }

    /**
     * The switch says "a business as well", so without a business it says
     * nothing and is refused rather than quietly meaning the installation
     * alone - which is what leaving --tenant out already means.
     */
    public function testTheSwitchWithoutABusinessIsRefused(): void
    {
        $container = $this->emptyInstallation();

        [$status, $output] = $this->outcomeOf($container, 'alice@example.com', alsoInstallation: true);

        self::assertSame(Command::FAILURE, $status, $output);
        self::assertStringContainsString('--tenant', $output);
        self::assertNull($container->getByType(Accounts::class)->withEmail('alice@example.com'));
    }

    /**
     * What the switch does not do is make an existing member of a business the
     * installation's administrator. Whether an account administers the
     * installation is said when it is made - see
     * Trilobit\Core\Domain\User\User - and the switch is not a way to say it
     * afterwards.
     */
    public function testAnAdministratorOfABusinessIsNotMadeBothAfterwards(): void
    {
        $container = $this->emptyInstallation();
        $this->execute($container, 'alice@example.com', tenant: self::HOST);

        [$status, $output] = $this->outcomeOf($container, 'alice@example.com', tenant: self::HOST, alsoInstallation: true);

        self::assertSame(Command::FAILURE, $status, $output);
        self::assertStringContainsString('administers a business', $output);

        $account = $container->getByType(Accounts::class)->withEmail('alice@example.com');
        self::assertInstanceOf(User::class, $account);
        self::assertFalse($account->isLandlord());
    }

    /** The password is shown once and nowhere else; the rest of the output is prose. */
    public function testThePasswordIsShownExactlyOnce(): void
    {
        $container = $this->emptyInstallation();

        $output = $this->execute($container, 'alice@example.com');

        self::assertSame(1, preg_match_all(AccountCommand::PASSWORD_LINE, $output));
    }

    /** And the same holds for the other shape, which prints one line more. */
    public function testThePasswordIsShownExactlyOnceForAnAdministratorOfABusinessToo(): void
    {
        $container = $this->emptyInstallation();

        $output = $this->execute($container, 'alice@example.com', tenant: self::HOST);

        self::assertSame(1, preg_match_all(AccountCommand::PASSWORD_LINE, $output));
    }

    public function testItNamesTheAccountWhenAskedTo(): void
    {
        $container = $this->emptyInstallation();

        $this->execute($container, 'alice@example.com', name: 'Alice Ammonite');

        $account = $container->getByType(Accounts::class)->withEmail('alice@example.com');

        self::assertInstanceOf(User::class, $account);
        self::assertSame('Alice Ammonite', $account->name());
    }

    /**
     * Run twice, it replaces the password of the account that is there rather
     * than refusing or making a second one - which is what a deployment script
     * calling it on every deploy needs, and what somebody who has forgotten
     * their password needs too.
     */
    public function testRunningItAgainReplacesThePasswordAndLeavesOneAccount(): void
    {
        $container = $this->emptyInstallation();

        $first = $this->passwordIn($this->execute($container, 'alice@example.com'));
        $second = $this->passwordIn($this->execute($container, 'alice@example.com'));

        self::assertNotSame($first, $second);

        $authenticator = $container->getByType(Authenticator::class);
        $identity = $authenticator->authenticate('alice@example.com', $second);
        self::assertInstanceOf(Identity::class, $identity);

        $entityManager = $container->getByType(EntityManagerInterface::class);
        self::assertCount(1, $entityManager->getRepository(User::class)->findAll());
        self::assertCount(0, $entityManager->getRepository(Role::class)->findAll());
    }

    /**
     * The same for the other shape, where running twice could also leave a
     * second role or a second membership - the second of which the database
     * would refuse, loudly, in the middle of a deployment.
     */
    public function testRunningItAgainForABusinessLeavesOneRoleAndOneMembership(): void
    {
        $container = $this->emptyInstallation();

        $this->execute($container, 'alice@example.com', tenant: self::HOST);
        $this->execute($container, 'alice@example.com', tenant: self::HOST);

        $entityManager = $container->getByType(EntityManagerInterface::class);

        self::assertCount(1, $entityManager->getRepository(User::class)->findAll());
        self::assertCount(1, $entityManager->getRepository(Role::class)->findAll());
        self::assertCount(1, $entityManager->getRepository(Membership::class)->findAll());
    }

    /**
     * Two runs at the same moment - two deployments, or two browser suites
     * preparing their accounts side by side - both find no owner's role and
     * both go to make it. The code is unique, so the database refuses the
     * second insert; what the second run has to do then is take the role the
     * first one made, rather than fail halfway through with an account and no
     * membership.
     *
     * The moment is made rather than hoped for. This test is the first run: it
     * inserts the role and holds its transaction open, which the command,
     * running in a process of its own, cannot see. That process finds no role,
     * goes to insert one and waits on this row; only once it is seen waiting is
     * the transaction committed, and the refusal the database then gives it is
     * the one CI met by chance. The row goes in with nothing granted, so that
     * the end of the test also shows the command made the role it took say the
     * whole of the application.
     */
    public function testARoleAnotherRunMadeMeanwhileIsTakenRatherThanMadeTwice(): void
    {
        $container = $this->emptyInstallation();
        $entityManager = $container->getByType(EntityManagerInterface::class);
        $connection = $entityManager->getConnection();

        $connection->beginTransaction();
        $connection->insert('core_role', ['code' => Role::OWNER, 'name' => 'Owner', 'permissions' => '[]']);

        [$met, $status, $output] = $this->committedOnceItWaits($connection, 'alice@example.com', self::HOST);

        self::assertTrue($met, 'the run never got as far as inserting the role, so it never met the other one: ' . $output);
        self::assertSame(Command::SUCCESS, $status, $output);

        $entityManager->clear();
        $roles = $entityManager->getRepository(Role::class)->findAll();
        self::assertCount(1, $roles);
        self::assertSame(Role::OWNER, $roles[0]->code());
        self::assertSame(['app:*'], $roles[0]->permissions());

        Tenants::switchTo($container, $this->business($container));
        $memberships = $entityManager->getRepository(Membership::class)->findAll();
        self::assertCount(1, $memberships);
        self::assertSame('alice@example.com', $memberships[0]->user()->email());
        self::assertSame($roles[0]->id(), $memberships[0]->role()->id());
    }

    /**
     * A fresh installation with one business in it, and nothing entered yet:
     * the command is what says which business it means, from the host it is
     * given.
     */
    private function emptyInstallation(): Container
    {
        $this->schema = Database::schemaFor(self::class);
        $container = Boot::coreAlone();
        Migrations::run($container);
        Tenants::create($container, 'Ammonite Bikes', self::HOST);

        // The signed-in user is asked for so that the container builds the
        // security services the same way a request would; the command itself
        // does not use it.
        self::assertInstanceOf(SignedIn::class, $container->getByType(SignedIn::class));

        return $this->container = $container;
    }

    private function business(Container $container): Tenant
    {
        $tenant = $container->getByType(EntityManagerInterface::class)
            ->getRepository(Tenant::class)
            ->findOneBy(['name' => 'Ammonite Bikes']);

        self::assertInstanceOf(Tenant::class, $tenant);

        return $tenant;
    }

    private function execute(
        Container $container,
        string $email,
        string $name = '',
        string $tenant = '',
        bool $alsoInstallation = false,
    ): string {
        [$status, $output] = $this->outcomeOf($container, $email, $name, $tenant, $alsoInstallation);

        self::assertSame(Command::SUCCESS, $status, $output);

        return $output;
    }

    /** @return array{int, string} */
    private function outcomeOf(
        Container $container,
        string $email,
        string $name = '',
        string $tenant = '',
        bool $alsoInstallation = false,
    ): array {
        $command = $container->getService('core.accountCommand');
        self::assertInstanceOf(Command::class, $command);
        new Application()->addCommand($command);

        $tester = new CommandTester($command);
        $arguments = ['email' => $email];
        if ($name !== '') {
            $arguments['--name'] = $name;
        }

        if ($tenant !== '') {
            $arguments['--tenant'] = $tenant;
        }

        if ($alsoInstallation) {
            $arguments['--also-installation'] = true;
        }

        $status = $tester->execute($arguments, ['capture_stderr_separately' => true]);

        return [$status, $tester->getDisplay() . $tester->getErrorOutput()];
    }

    /**
     * `bin/trilobit app:account` run the way a deployment runs it, in a process
     * of its own with a connection of its own, while $connection holds an
     * uncommitted row - which is committed the moment the other process is
     * seen inserting the same role, and so waiting on it.
     *
     * The waiting is asked of the server rather than guessed from the time that
     * has passed, because the interleaving is what the test is about: without
     * it the run would simply have found the role, and a pass would say
     * nothing. Whether it was seen is therefore returned, for the caller to
     * hold the test to. A process that has already ended never will get there,
     * so that ends the wait early rather than at the deadline.
     *
     * The transaction is committed whatever happened, before anything is
     * asserted: a failure left holding it would leave the other process
     * waiting and the schema impossible to drop.
     *
     * The schema this test made is in the environment the process inherits;
     * see Trilobit\Tests\Database::schemaFor().
     *
     * @return array{bool, int, string} whether it was seen waiting, its exit code, and what it printed
     */
    private function committedOnceItWaits(Connection $connection, string $email, string $tenant): array
    {
        $process = proc_open(
            [PHP_BINARY, Bootstrap::rootDirectory() . '/bin/trilobit', 'app:account', $email, '--tenant', $tenant, '--no-ansi'],
            [1 => ['pipe', 'w'], 2 => ['pipe', 'w']],
            $pipes,
            Bootstrap::rootDirectory(),
        );

        try {
            self::assertIsResource($process);

            $met = false;
            $deadline = microtime(true) + self::SECONDS_TO_REACH_THE_INSERT;
            while (!$met && microtime(true) < $deadline && proc_get_status($process)['running']) {
                $waiting = $connection->fetchOne(
                    'SELECT COUNT(*) FROM information_schema.PROCESSLIST'
                    . ' WHERE ID <> CONNECTION_ID() AND DB = DATABASE() AND INFO LIKE ?',
                    ['INSERT INTO core_role%'],
                );
                $met = is_numeric($waiting) && (int) $waiting > 0;
                if (!$met) {
                    usleep(20_000);
                }
            }
        } finally {
            $connection->commit();
        }

        $output = '';
        foreach ($pipes as $pipe) {
            $output .= (string) stream_get_contents($pipe);
            fclose($pipe);
        }

        // The exit code is read off the status, because proc_close() has
        // nothing left to report for a process a status call has already seen
        // end.
        $status = proc_get_status($process);
        while ($status['running']) {
            usleep(10_000);
            $status = proc_get_status($process);
        }

        proc_close($process);

        return [$met, $status['exitcode'], $output];
    }

    private function passwordIn(string $output): string
    {
        preg_match(AccountCommand::PASSWORD_LINE, $output, $match);
        $password = $match[1] ?? '';

        self::assertNotSame('', $password, 'the command printed nothing to sign in with: ' . $output);

        return $password;
    }
}
