<?php

declare(strict_types=1);

namespace Trilobit\Cms\Presentation\Admin;

/**
 * Makes the list of pages for Trilobit\Cms\Presentation\Admin\PagePresenter.
 *
 * Generated by the container (see CmsExtension), so that the presenter is
 * handed the one thing it draws rather than the services the listing is made
 * of.
 */
interface PageListingFactory
{
    public function create(): PageListing;
}
