<?php

declare(strict_types=1);

namespace Trilobit\Core\Presentation\Admin;

/**
 * Makes the list of people for Trilobit\Core\Presentation\Admin\PeoplePresenter.
 *
 * Generated by the container (see CoreExtension), so that the presenter is
 * handed the one thing it draws rather than the services the listing is made
 * of.
 */
interface PeopleListingFactory
{
    public function create(): PeopleListing;
}
